package com.eevajonna.graphexample.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF006590)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFC8E6FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001E2F)
val md_theme_light_secondary = Color(0xFF6E5E00)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFE254)
val md_theme_light_onSecondaryContainer = Color(0xFF211B00)
val md_theme_light_tertiary = Color(0xFFB90065)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFD9E2)
val md_theme_light_onTertiaryContainer = Color(0xFF3E001E)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF24005A)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF24005A)
val md_theme_light_surfaceVariant = Color(0xFFDDE3EA)
val md_theme_light_onSurfaceVariant = Color(0xFF41484D)
val md_theme_light_outline = Color(0xFF71787E)
val md_theme_light_inverseOnSurface = Color(0xFFF6EDFF)
val md_theme_light_inverseSurface = Color(0xFF3A1D71)
val md_theme_light_inversePrimary = Color(0xFF88CEFF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF006590)
val md_theme_light_outlineVariant = Color(0xFFC1C7CE)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF88CEFF)
val md_theme_dark_onPrimary = Color(0xFF00344D)
val md_theme_dark_primaryContainer = Color(0xFF004C6E)
val md_theme_dark_onPrimaryContainer = Color(0xFFC8E6FF)
val md_theme_dark_secondary = Color(0xFFE4C500)
val md_theme_dark_onSecondary = Color(0xFF393000)
val md_theme_dark_secondaryContainer = Color(0xFF534600)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFE254)
val md_theme_dark_tertiary = Color(0xFFFFB0C9)
val md_theme_dark_onTertiary = Color(0xFF650034)
val md_theme_dark_tertiaryContainer = Color(0xFF8E004C)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFD9E2)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF24005A)
val md_theme_dark_onBackground = Color(0xFFEADDFF)
val md_theme_dark_surface = Color(0xFF24005A)
val md_theme_dark_onSurface = Color(0xFFEADDFF)
val md_theme_dark_surfaceVariant = Color(0xFF41484D)
val md_theme_dark_onSurfaceVariant = Color(0xFFC1C7CE)
val md_theme_dark_outline = Color(0xFF8B9198)
val md_theme_dark_inverseOnSurface = Color(0xFF24005A)
val md_theme_dark_inverseSurface = Color(0xFFEADDFF)
val md_theme_dark_inversePrimary = Color(0xFF006590)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF88CEFF)
val md_theme_dark_outlineVariant = Color(0xFF41484D)
val md_theme_dark_scrim = Color(0xFF000000)

val seed = Color(0xFF2CB8FF)
